export const TEST_TOTAL_INCREMENT = 'TEST_TOTAL_INCREMENT';
export const TEST_SCORE_INCREMENT = 'TEST_SCORE_INCREMENT';
export const TEST_TOTAL_RESET = 'TEST_TOTAL_RESET';
export const TEST_SCORE_RESET = 'TEST_SCORE_RESET';
