export const WORDS_FETCH_START = 'WORDS_FETCH_START';
export const WORDS_FETCH_SUCCESS = 'WORDS_FETCH_SUCCESS';
export const WORDS_FETCH_FAILURE = 'WORDS_FETCH_FAILURE';

export const WORDS_ADD_START = 'WORDS_ADD_START';
export const WORDS_ADD_SUCCESS = 'WORDS_ADD_SUCCESS';
export const WORDS_ADD_FAILURE = 'WORDS_ADD_FAILURE';

export const WORDS_FETCH_ERROR = 'WORDS_FETCH_ERROR';
